/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/exercises/Books': RouteRecordInfo<'/exercises/Books', '/exercises/Books', Record<never, never>, Record<never, never>>,
    '/exercises/BooksDetailPage': RouteRecordInfo<'/exercises/BooksDetailPage', '/exercises/BooksDetailPage', Record<never, never>, Record<never, never>>,
    '/exercises/BooksPage': RouteRecordInfo<'/exercises/BooksPage', '/exercises/BooksPage', Record<never, never>, Record<never, never>>,
    '/exercises/customRating': RouteRecordInfo<'/exercises/customRating', '/exercises/customRating', Record<never, never>, Record<never, never>>,
    '/exercises/customTooltip': RouteRecordInfo<'/exercises/customTooltip', '/exercises/customTooltip', Record<never, never>, Record<never, never>>,
    '/exercises/renderFunctions': RouteRecordInfo<'/exercises/renderFunctions', '/exercises/renderFunctions', Record<never, never>, Record<never, never>>,
    '/exercises/taskItem': RouteRecordInfo<'/exercises/taskItem', '/exercises/taskItem', Record<never, never>, Record<never, never>>,
    '/exercises/todolist': RouteRecordInfo<'/exercises/todolist', '/exercises/todolist', Record<never, never>, Record<never, never>>,
    '/exercises/useLocalStorage': RouteRecordInfo<'/exercises/useLocalStorage', '/exercises/useLocalStorage', Record<never, never>, Record<never, never>>,
    '/exercises/userCard': RouteRecordInfo<'/exercises/userCard', '/exercises/userCard', Record<never, never>, Record<never, never>>,
    '/lecture/': RouteRecordInfo<'/lecture/', '/lecture', Record<never, never>, Record<never, never>>,
    '/lecture/composables': RouteRecordInfo<'/lecture/composables', '/lecture/composables', Record<never, never>, Record<never, never>>,
    '/lecture/day2-1': RouteRecordInfo<'/lecture/day2-1', '/lecture/day2-1', Record<never, never>, Record<never, never>>,
    '/lecture/day2-2': RouteRecordInfo<'/lecture/day2-2', '/lecture/day2-2', Record<never, never>, Record<never, never>>,
    '/lecture/day2-3': RouteRecordInfo<'/lecture/day2-3', '/lecture/day2-3', Record<never, never>, Record<never, never>>,
    '/lecture/day2-4': RouteRecordInfo<'/lecture/day2-4', '/lecture/day2-4', Record<never, never>, Record<never, never>>,
    '/lecture/day2-5': RouteRecordInfo<'/lecture/day2-5', '/lecture/day2-5', Record<never, never>, Record<never, never>>,
    '/lecture/day2-6': RouteRecordInfo<'/lecture/day2-6', '/lecture/day2-6', Record<never, never>, Record<never, never>>,
    '/lecture/day2-7': RouteRecordInfo<'/lecture/day2-7', '/lecture/day2-7', Record<never, never>, Record<never, never>>,
    '/lecture/day2-8': RouteRecordInfo<'/lecture/day2-8', '/lecture/day2-8', Record<never, never>, Record<never, never>>,
    '/lecture/day2-9': RouteRecordInfo<'/lecture/day2-9', '/lecture/day2-9', Record<never, never>, Record<never, never>>,
    '/lecture/day3-1-vfor': RouteRecordInfo<'/lecture/day3-1-vfor', '/lecture/day3-1-vfor', Record<never, never>, Record<never, never>>,
    '/lecture/day4-lifecycle_hooks': RouteRecordInfo<'/lecture/day4-lifecycle_hooks', '/lecture/day4-lifecycle_hooks', Record<never, never>, Record<never, never>>,
    '/lecture/day4-v-model': RouteRecordInfo<'/lecture/day4-v-model', '/lecture/day4-v-model', Record<never, never>, Record<never, never>>,
    '/lecture/day5': RouteRecordInfo<'/lecture/day5', '/lecture/day5', Record<never, never>, Record<never, never>>,
    '/lecture/day5_v-model': RouteRecordInfo<'/lecture/day5_v-model', '/lecture/day5_v-model', Record<never, never>, Record<never, never>>,
    '/lecture/day6-renderFunctions': RouteRecordInfo<'/lecture/day6-renderFunctions', '/lecture/day6-renderFunctions', Record<never, never>, Record<never, never>>,
    '/lecture/day6-scopedSlots': RouteRecordInfo<'/lecture/day6-scopedSlots', '/lecture/day6-scopedSlots', Record<never, never>, Record<never, never>>,
    '/lecture/day6-slots': RouteRecordInfo<'/lecture/day6-slots', '/lecture/day6-slots', Record<never, never>, Record<never, never>>,
    '/lecture/directives': RouteRecordInfo<'/lecture/directives', '/lecture/directives', Record<never, never>, Record<never, never>>,
    '/lecture/hands_on2': RouteRecordInfo<'/lecture/hands_on2', '/lecture/hands_on2', Record<never, never>, Record<never, never>>,
    '/lecture/hands-on': RouteRecordInfo<'/lecture/hands-on', '/lecture/hands-on', Record<never, never>, Record<never, never>>,
    '/lecture/store-structure': RouteRecordInfo<'/lecture/store-structure', '/lecture/store-structure', Record<never, never>, Record<never, never>>,
  }
}
