/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BookList: typeof import('./components/BookList.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    CustomList: typeof import('./components/CustomList.vue')['default']
    CustomRating: typeof import('./components/CustomRating.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RenderComponent: typeof import('./components/RenderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
