/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    CustomRating: typeof import('./components/CustomRating.vue')['default']
    Day2: typeof import('./components/day2.vue')['default']
    Day21: typeof import('./components/day2-1.vue')['default']
    Day22: typeof import('./components/day2-2.vue')['default']
    Day23: typeof import('./components/day2-3.vue')['default']
    Day24: typeof import('./components/day2-4.vue')['default']
    Day25: typeof import('./components/day2-5.vue')['default']
    Day26: typeof import('./components/day2-6.vue')['default']
    Day27: typeof import('./components/day2-7.vue')['default']
    Day28: typeof import('./components/day2-8.vue')['default']
    Day29: typeof import('./components/day2-9.vue')['default']
    Day31Vfor: typeof import('./components/day3-1-vfor.vue')['default']
    Day4Lifecycle_hooks: typeof import('./components/day4-lifecycle_hooks.vue')['default']
    Day4VModel: typeof import('./components/day4-v-model.vue')['default']
    Day5: typeof import('./components/day5.vue')['default']
    Day5Component: typeof import('./components/day5-component.vue')['default']
    Hands_on2: typeof import('./components/hands_on2.vue')['default']
    HandsOn: typeof import('./components/hands-on.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TaskItemComp: typeof import('./components/taskItem-comp.vue')['default']
    Todolist: typeof import('./components/todolist.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserCardComponent: typeof import('./components/userCard-component.vue')['default']
  }
}
