/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/exercises/customRating': RouteRecordInfo<'/exercises/customRating', '/exercises/customRating', Record<never, never>, Record<never, never>>,
    '/exercises/taskItem': RouteRecordInfo<'/exercises/taskItem', '/exercises/taskItem', Record<never, never>, Record<never, never>>,
    '/exercises/todolist': RouteRecordInfo<'/exercises/todolist', '/exercises/todolist', Record<never, never>, Record<never, never>>,
    '/exercises/userCard': RouteRecordInfo<'/exercises/userCard', '/exercises/userCard', Record<never, never>, Record<never, never>>,
    '/gamuda/': RouteRecordInfo<'/gamuda/', '/gamuda', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-1': RouteRecordInfo<'/gamuda/day2-1', '/gamuda/day2-1', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-2': RouteRecordInfo<'/gamuda/day2-2', '/gamuda/day2-2', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-3': RouteRecordInfo<'/gamuda/day2-3', '/gamuda/day2-3', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-4': RouteRecordInfo<'/gamuda/day2-4', '/gamuda/day2-4', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-5': RouteRecordInfo<'/gamuda/day2-5', '/gamuda/day2-5', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-6': RouteRecordInfo<'/gamuda/day2-6', '/gamuda/day2-6', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-7': RouteRecordInfo<'/gamuda/day2-7', '/gamuda/day2-7', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-8': RouteRecordInfo<'/gamuda/day2-8', '/gamuda/day2-8', Record<never, never>, Record<never, never>>,
    '/gamuda/day2-9': RouteRecordInfo<'/gamuda/day2-9', '/gamuda/day2-9', Record<never, never>, Record<never, never>>,
    '/gamuda/day3-1-vfor': RouteRecordInfo<'/gamuda/day3-1-vfor', '/gamuda/day3-1-vfor', Record<never, never>, Record<never, never>>,
    '/gamuda/day4-lifecycle_hooks': RouteRecordInfo<'/gamuda/day4-lifecycle_hooks', '/gamuda/day4-lifecycle_hooks', Record<never, never>, Record<never, never>>,
    '/gamuda/day4-v-model': RouteRecordInfo<'/gamuda/day4-v-model', '/gamuda/day4-v-model', Record<never, never>, Record<never, never>>,
    '/gamuda/day5': RouteRecordInfo<'/gamuda/day5', '/gamuda/day5', Record<never, never>, Record<never, never>>,
    '/gamuda/day5_v-model': RouteRecordInfo<'/gamuda/day5_v-model', '/gamuda/day5_v-model', Record<never, never>, Record<never, never>>,
    '/gamuda/hands_on2': RouteRecordInfo<'/gamuda/hands_on2', '/gamuda/hands_on2', Record<never, never>, Record<never, never>>,
    '/gamuda/hands-on': RouteRecordInfo<'/gamuda/hands-on', '/gamuda/hands-on', Record<never, never>, Record<never, never>>,
  }
}
