/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/lecture/': RouteRecordInfo<'/lecture/', '/lecture', Record<never, never>, Record<never, never>>,
    '/lecture/day4-lifecycle_hooks': RouteRecordInfo<'/lecture/day4-lifecycle_hooks', '/lecture/day4-lifecycle_hooks', Record<never, never>, Record<never, never>>,
    '/lecture/day4-v-model': RouteRecordInfo<'/lecture/day4-v-model', '/lecture/day4-v-model', Record<never, never>, Record<never, never>>,
    '/lecture/day5': RouteRecordInfo<'/lecture/day5', '/lecture/day5', Record<never, never>, Record<never, never>>,
    '/lecture/day5_v-model': RouteRecordInfo<'/lecture/day5_v-model', '/lecture/day5_v-model', Record<never, never>, Record<never, never>>,
    '/lecture/day6-slots': RouteRecordInfo<'/lecture/day6-slots', '/lecture/day6-slots', Record<never, never>, Record<never, never>>,
    '/lecture/hands_on2': RouteRecordInfo<'/lecture/hands_on2', '/lecture/hands_on2', Record<never, never>, Record<never, never>>,
    '/lecture/hands-on': RouteRecordInfo<'/lecture/hands-on', '/lecture/hands-on', Record<never, never>, Record<never, never>>,
  }
}
